# -*- coding: utf-8 -*-
"""Password_Generator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Gu11SgP6MK-foiYFpse_vpw0y2OsvOi2
"""

'''
                       Password Generator
-------------------------------------------------------------
'''
import secrets
import string
def create_pw(pw_length=12):
   letters = string.ascii_letters
   digits = string.digits
   special_chars = string.punctuation
   alphabet = letters + digits + special_chars
   pwd = ''
   pw_strong = False
   while not pw_strong:
       pwd = ''
       for i in range(pw_length):
           pwd += ''.join(secrets.choice(alphabet))

       if (any(char in special_chars for char in pwd) and
               sum(char in digits for char in pwd) >= 2):
           pw_strong = True
   return pwd
if __name__ == '__main__':
   print(create_pw())